name: Deploy
on:
  workflow_dispatch:
    inputs:
      env-name:
        type: environment
        required: true
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        stage: [dev, stg, prod]
        isManual:
          - ${{ github.event_name == 'workflow_dispatch' }}
        exclude:
          - isManual: true
        include:
          # Re-include only the selected environment for manual trigger
          - stage: ${{ inputs.env-name }}
            isManual: true
    environment: ${{ matrix.stage }}
    env:
      STAGE: ${{ matrix.stage }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: echo $STAGE
