name: Deploy
on:
  workflow_dispatch:
    inputs:
      env-name:
        type: environment
        required: true
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        stage: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', inputs.env-name)) || fromJSON('["dev", "stg", "prod"]') }}
    environment: ${{ matrix.stage }}
    env:
      STAGE: ${{ matrix.stage }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: echo $STAGE
